name: Release

on:
  release:
    types:
    - released

jobs:
  upload-assets:
    name: Upload Assets to Release
    runs-on: ubuntu-22.04
    steps:
    - uses: AButler/upload-release-assets@v3.0
      with:
        files: "proxy-management-full.js;proxy-management-lite.js"
        repo-token: ${{ secrets.API_TOKEN_GITHUB }}
        release-tag: ${{ needs.package.outputs.version }}
  