name: Release

on:
  release:
    types:
    - released

jobs:
  upload-assets:
    name: Upload Assets to Release
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Update files for version ${{github.ref_name}}
      working-directory: ./scripts
      run: |
        mv proxy-management-lite.js proxy-management-lite-${{github.ref_name}}.js
        mv proxy-management-full.js proxy-management-full-${{github.ref_name}}.js
        mv subscription-converter.js subscription-converter-${{github.ref_name}}.js
    - uses: AButler/upload-release-assets@v3.0
      with:
        files: "scripts/proxy-management-lite-${{github.ref_name}}.js;scripts/proxy-management-full-${{github.ref_name}}.js;scripts/subscription-converter-${{github.ref_name}}.js"
        repo-token: ${{ secrets.API_TOKEN_GITHUB }}
        release-tag: ${{ needs.package.outputs.version }}
  